// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjx8NKcbMyVsH6Hp_3ODxwHbrd1IN906w',
    appId: '1:714464476418:web:bb1b2ae84898c5c97d961b',
    messagingSenderId: '714464476418',
    projectId: 'beastmodeapp-7dec9',
    authDomain: 'beastmodeapp-7dec9.firebaseapp.com',
    storageBucket: 'beastmodeapp-7dec9.firebasestorage.app',
    measurementId: 'G-PCG55NYQ18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRx9B9dGiDUrnnj9-mqlmnZjqC2yL7a8Q',
    appId: '1:714464476418:android:7ddf751029c1685a7d961b',
    messagingSenderId: '714464476418',
    projectId: 'beastmodeapp-7dec9',
    storageBucket: 'beastmodeapp-7dec9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy2GZBy8kl_FvI_U4Edad8evTHfDEr9yU',
    appId: '1:714464476418:ios:a6e413ede1006d137d961b',
    messagingSenderId: '714464476418',
    projectId: 'beastmodeapp-7dec9',
    storageBucket: 'beastmodeapp-7dec9.firebasestorage.app',
    iosBundleId: 'com.example.beastMode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy2GZBy8kl_FvI_U4Edad8evTHfDEr9yU',
    appId: '1:714464476418:ios:a6e413ede1006d137d961b',
    messagingSenderId: '714464476418',
    projectId: 'beastmodeapp-7dec9',
    storageBucket: 'beastmodeapp-7dec9.firebasestorage.app',
    iosBundleId: 'com.example.beastMode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjx8NKcbMyVsH6Hp_3ODxwHbrd1IN906w',
    appId: '1:714464476418:web:d46580cbd445b00a7d961b',
    messagingSenderId: '714464476418',
    projectId: 'beastmodeapp-7dec9',
    authDomain: 'beastmodeapp-7dec9.firebaseapp.com',
    storageBucket: 'beastmodeapp-7dec9.firebasestorage.app',
    measurementId: 'G-TRDQH3JGK8',
  );
}
